import { createHash, randomBytes, randomUUID } from "node:crypto";
import { ensureSchema, sql } from "./db";
import { sendReviewNotification } from "./mailer";
export type PublicReview = { id: string; instagramUsername: string; review: string; createdAt: string };
const hashToken = (token: string) => createHash("sha256").update(token).digest("hex");
const siteUrl = () => (process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000").replace(/\/$/, "");
export async function getApprovedReviews(): Promise<PublicReview[]> { if (!process.env.DATABASE_URL) return []; try { await ensureSchema(); const rows = await sql`SELECT id, instagram_username, review, created_at FROM reviews WHERE status = 'APPROVED' ORDER BY created_at DESC`; return rows.map((row) => ({ id: String(row.id), instagramUsername: String(row.instagram_username), review: String(row.review), createdAt: new Date(String(row.created_at)).toISOString() })); } catch (error) { console.error("Unable to load approved reviews", error); return []; } }
export async function isDuplicateReview(username: string, review: string) { await ensureSchema(); const rows = await sql`SELECT id FROM reviews WHERE instagram_username = ${username} AND review = ${review} AND created_at > NOW() - INTERVAL '30 days' LIMIT 1`; return rows.length > 0; }
export async function createPendingReview(username: string, review: string) { await ensureSchema(); const reviewId = randomUUID(); const approveToken = randomBytes(32).toString("hex"); const rejectToken = randomBytes(32).toString("hex"); const expiresAt = new Date(Date.now() + 72 * 60 * 60 * 1000); await sql.begin(async (transaction) => { await transaction`INSERT INTO reviews (id, instagram_username, review, status) VALUES (${reviewId}, ${username}, ${review}, 'PENDING')`; await transaction`INSERT INTO review_actions (id, review_id, token_hash, action, expires_at) VALUES (${randomUUID()}, ${reviewId}, ${hashToken(approveToken)}, 'approve', ${expiresAt})`; await transaction`INSERT INTO review_actions (id, review_id, token_hash, action, expires_at) VALUES (${randomUUID()}, ${reviewId}, ${hashToken(rejectToken)}, 'reject', ${expiresAt})`; }); await sendReviewNotification({ username, review, approveUrl: `${siteUrl()}/api/reviews/action?token=${approveToken}`, rejectUrl: `${siteUrl()}/api/reviews/action?token=${rejectToken}` }); }
export async function processReviewAction(token: string) { if (!token) return { status: "invalid" as const, message: "This approval link is invalid." }; await ensureSchema(); const rows = await sql`SELECT ra.review_id, ra.action, ra.expires_at, ra.used_at, r.status FROM review_actions ra JOIN reviews r ON r.id = ra.review_id WHERE ra.token_hash = ${hashToken(token)} LIMIT 1`; const action = rows[0]; if (!action) return { status: "invalid" as const, message: "This approval link is invalid." }; if (action.used_at || new Date(String(action.expires_at)).getTime() < Date.now()) return { status: "expired" as const, message: "This approval link has expired or has already been used." }; if (action.status !== "PENDING") return { status: "processed" as const, message: `This review has already been ${String(action.status).toLowerCase()}.` }; const nextStatus = action.action === "approve" ? "APPROVED" : "REJECTED"; await sql.begin(async (transaction) => { await transaction`UPDATE reviews SET status = ${nextStatus}, updated_at = NOW() WHERE id = ${action.review_id} AND status = 'PENDING'`; await transaction`UPDATE review_actions SET used_at = NOW() WHERE review_id = ${action.review_id} AND used_at IS NULL`; }); return { status: action.action as "approve" | "reject", message: nextStatus === "APPROVED" ? "Review approved successfully." : "Review rejected successfully." }; }
